<Test>
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<TestList>
    viewclass: 'Note'
    SingleSelectableRecycleBoxLayout:

<SaveTestDialog>:
    title: 'Save Tests'
    title_align: 'center'
    size_hint: (0.9, 0.9)
    BoxLayout:
        orientation: "vertical"

        FileChooserIconView:
            id: filechooser
            path: '/mnt/usbStick' # str(Path.home())
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()
            Button:
                text: "Save"
                on_release: root.save(filechooser.path)

<TestsScreen>:
	name: 'tests_screen'
    GranuContainer:
        GranuSideArea:
            id: tests_buttons
        GranuContent:
            GranuTitle:
                text: 'Tests'
            BoxLayout:
                orientation: 'horizontal'
                NoteList:
                    id: tests_list
                    on_interaction:
                        root.test_buttons()
                    on_deselect_all:
                        root.default_buttons()
