<GranuContainer>
	orientation: 'horizontal'
	padding: 10

<GranuSideArea>
	rows: 4
	spacing: [0, 10]
	row_default_height: self.height/4 - (30/4.)
	row_force_default: True
	size_hint_x: 0.37

<GranuSideButton>
	font_size: 40
	halign: 'center'
	valign: 'middle'

<GranuContent>
	orientation: 'vertical'
	padding: [10, 0, 0, 0]
	spacing: 10

<GranuTitle>
    size_hint_max_y: 50
    font_size: 40

